SURGE_LOGIN: chenh0886@gmail.com
SURGE_TOKEN: 2f5e35560a3eebd09fb15395fa8e26df

language: node_js
node_js:
  - "6"

deploy:
  provider: surge
  project: ./dist
  domain: spiky-goldfish.surge.sh